"""
whatif_engine.py -- live what-if simulation for AeroTwin.

Given the current sensor window, lets an operator ask "what happens to
my remaining useful life if I take this action now?" for a small set of
named, physically-motivated scenarios (throttle back, climb to cooler
air, continue as-is, etc).

DESIGN (v2 -- counterfactual regeneration, not raw-value scaling):
The original version multiplied sensor values in the current window by
fixed factors (e.g. rpm *= 0.85) and re-fed that into the RUL model.
That failed: the model was trained purely on correlation between raw
sensor magnitude and remaining life, so artificially lowering values
produces an OUT-OF-DISTRIBUTION input that looks statistically similar
to "the tail end of a real degrading flight" -- not "operator safely
reduced throttle". Every scenario collapsed toward near-zero RUL because
the model had no way to distinguish a deliberate safe reduction from
the engine actually failing.

FIX: instead of perturbing raw values, each scenario REGENERATES the
future portion of the flight using the SAME fault injector the model
was trained on, with the fault's `severity` parameter reduced (e.g.
0.35 instead of 1.0 -- "if this intervention slows the fault's
progression"). This keeps every input inside the training distribution,
because it's generated by literally the same process the model learned
from -- only the severity differs. The delta between scenarios is then
a genuine, causally meaningful model output, not an artifact of feeding
the model nonsense.

Each scenario uses the SAME random seed for the healthy baseline and the
injector's internal noise, so the only thing that differs between
scenarios is severity -- isolating its effect instead of comparing two
different random noise realizations.

CURRENT STATUS: wired to Ashmitha's calibrated RUL ensemble
(train_rul_ensemble.py's predict_rul_ensemble/load_ensemble), loaded
once at import time via load_ensemble(). calibrated=True is the
ensemble's default, so point_estimate_minutes and rul_lower_bound_minutes
are Step B's bias-corrected values; std_minutes is always the raw
ensemble spread regardless of calibration. Everything else (SCENARIOS,
run_whatif) is unchanged, since predict_rul_ensemble returns the same
{point_estimate_minutes, rul_lower_bound_minutes, std_minutes} shape
_predict() maps into here.

KNOWN CAVEAT (per Ashmitha): the (250,350) RUL-minute calibration bucket
has zero validation windows, so calibration there is a no-op (raw
estimate, no correction) -- it passes the coverage check on a
technicality, not because it's meaningfully calibrated. Worth keeping in
mind if a what-if scenario's point estimate lands in that range.

Run directly for a demo/sanity check: python models/rul/whatif_engine.py
"""
import os
import sys

import numpy as np
import pandas as pd

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))
from schema import SENSOR_FIELDS, WINDOW_SIZE

from models.rul.train_rul_ensemble import (
    predict_rul_ensemble,
    load_ensemble,
    build_inference_window,
)  # noqa: E402

_MODEL_DIR = os.path.dirname(os.path.abspath(__file__))
_models, _scaler, _dropped_idx_list = load_ensemble(model_dir=_MODEL_DIR)

sys.path.insert(0, os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))), "simulator"))
from simulate_healthy import simulate_healthy_flight  # noqa: E402
from fault_injectors import INJECTORS  # noqa: E402


# ---------------------------------------------------------------------------
# Scenario definitions -- severity multipliers applied to the ONGOING fault,
# not sensor-specific scaling. Physically: an operator action (reduce
# throttle, adjust cooling, cut vibration load) is modeled as slowing how
# severely the current fault progresses from this point forward. This
# applies uniformly regardless of which of the 6 fault types is active,
# which is operationally reasonable (throttle reduction generically eases
# stress on a degrading engine) and keeps every scenario's input inside
# the training distribution.
# ---------------------------------------------------------------------------

SCENARIOS = {
    "continue_current": {
        "label": "Continue current profile",
        "severity_multiplier": 1.0,   # no intervention -- fault progresses as-is
    },
    "reduce_throttle": {
        "label": "Reduce throttle now",
        "severity_multiplier": 0.35,
    },
    "climb_cooler_air": {
        "label": "Climb to cooler air / adjust cooling",
        "severity_multiplier": 0.5,
    },
    "reduce_vibration_load": {
        "label": "Reduce RPM to cut vibration load",
        "severity_multiplier": 0.45,
    },
}


def _regenerate_window(fault_type, onset_idx, duration, window_start, severity, seed):
    """
    Regenerates a full counterfactual flight (same fault_type, onset_idx,
    duration, and random seed as the real flight -- only severity varies),
    then extracts the window at [window_start : window_start + WINDOW_SIZE].

    fault_type == "none" (currently healthy, no fault active): severity has
    no effect, just returns a healthy window -- every scenario is identical
    in this case, which is correct (nothing to intervene on).
    """
    healthy = simulate_healthy_flight(duration_timesteps=duration, seed=seed)

    if fault_type == "none" or fault_type not in INJECTORS:
        counterfactual = healthy
    else:
        onset_frac = onset_idx / max(1, duration - 1)
        injector = INJECTORS[fault_type]
        counterfactual = injector(healthy, onset_frac=onset_frac, severity=severity, seed=seed)

    window = counterfactual[SENSOR_FIELDS].to_numpy(dtype=np.float32)[
        window_start:window_start + WINDOW_SIZE
    ]
    return window


def _predict_raw(window):
    """Unclamped ensemble output dict -- used internally so delta comparisons
    in run_whatif() are computed on the raw point estimate. Keeping this as
    a dict (not a bare float) preserves rul_lower_bound_minutes and
    std_minutes for _predict() to pass through."""
    featurized = build_inference_window(window)
    return predict_rul_ensemble(featurized, _models, _scaler, _dropped_idx_list)


def _predict(window):
    """
    Wraps the ensemble's {point_estimate_minutes, rul_lower_bound_minutes,
    std_minutes} output into the shape run_whatif() expects.
    point_estimate_minutes and rul_lower_bound_minutes are clamped at 0
    (RUL can't be negative) for display, but delta comparisons in
    run_whatif() use the raw (unclamped) value so real scenario differences
    don't get erased by the clamp near end-of-flight.
    """
    result = _predict_raw(window)
    raw = result["point_estimate_minutes"]
    return {
        "point_estimate_minutes": max(0.0, raw),
        "rul_lower_bound_minutes": max(0.0, result["rul_lower_bound_minutes"]),
        "std_minutes": result["std_minutes"],
        "_raw": raw,
    }


def run_whatif(fault_type, onset_idx, duration, window_start, seed=42, scenario_names=None):
    """
    fault_type, onset_idx, duration: read straight from the real flight's
        CSV columns (fault_type, fault_onset_idx, and len(df) respectively).
    window_start: index of the current window's first row within the flight
        (e.g. the "now" point an operator is asking about).
    seed: fixed across all scenarios so only severity differs between them --
        isolates the causal effect of the intervention from random noise.
    scenario_names: list of scenario keys to evaluate; defaults to all.

    Returns a list of dicts, one per scenario, each with:
        - scenario, label
        - point_estimate_minutes, rul_lower_bound_minutes, std_minutes
        - delta_minutes: change vs "continue_current" baseline, computed
          on UNCLAMPED raw values so it stays meaningful near end-of-flight
    """
    if scenario_names is None:
        scenario_names = list(SCENARIOS.keys())
    if "continue_current" not in scenario_names:
        scenario_names = ["continue_current"] + scenario_names

    results = []
    baseline_estimate = None

    for name in scenario_names:
        severity = SCENARIOS[name]["severity_multiplier"]
        window = _regenerate_window(fault_type, onset_idx, duration, window_start, severity, seed)
        prediction = _predict(window)

        if name == "continue_current":
            baseline_estimate = prediction["_raw"]

        results.append({
            "scenario": name,
            "label": SCENARIOS[name]["label"],
            "point_estimate_minutes": prediction["point_estimate_minutes"],
            "rul_lower_bound_minutes": prediction["rul_lower_bound_minutes"],
            "std_minutes": prediction["std_minutes"],
            "delta_minutes": prediction["_raw"] - baseline_estimate,
        })

    return results


# ---------------------------------------------------------------------------
# Demo / sanity check
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    import glob

    print("Loading a sample flight to read its fault metadata for a what-if demo...")
    csv_paths = sorted(glob.glob(os.path.join("data", "raw", "*.csv")))
    if not csv_paths:
        print("No flights found in data/raw -- run simulator/fault_injectors.py first.")
        sys.exit(1)

    # pick a fault flight (not a healthy-only one) so there's something to intervene on
    sample_path = next((p for p in csv_paths if "healthy" not in os.path.basename(p)), csv_paths[0])
    df = pd.read_csv(sample_path).sort_values("timestamp").reset_index(drop=True)

    fault_type = df["fault_type"].iloc[df["fault_onset_idx"].iloc[0] + 5] if df["fault_onset_idx"].iloc[0] >= 0 else "none"
    # more robust: just take the most common non-"none" fault_type label in this flight
    non_none = df[df["fault_type"] != "none"]["fault_type"]
    fault_type = non_none.mode().iloc[0] if len(non_none) > 0 else "none"

    onset_idx = int(df["fault_onset_idx"].iloc[0])
    duration = len(df)

    # A point well INTO the fault's progression (not just the flight's
    # midpoint) -- the convex degradation curve is deliberately near-zero
    # right after onset, so severity differences only become visible once
    # meaningful progress has accumulated. Using 70% of the way from onset
    # to end-of-flight leaves enough runway for scenarios to still differ
    # without being all the way at true failure.
    window_start = onset_idx + int(0.7 * (duration - onset_idx))
    window_start = min(window_start, duration - WINDOW_SIZE)  # stay in bounds

    print(f"Flight: {os.path.basename(sample_path)}  |  fault_type={fault_type}  "
          f"onset_idx={onset_idx}  duration={duration}  window_start={window_start}\n")
    print("Running against Ashmitha's calibrated RUL ensemble "
          "(calibrated=True, per-bucket bias correction + conformal bounds).\n")

    results = run_whatif(fault_type, onset_idx, duration, window_start)

    for r in results:
        print(f"{r['label']:<35} "
              f"point_est={r['point_estimate_minutes']:7.1f}  "
              f"delta={r['delta_minutes']:+7.1f}")